# Generated by Django 5.2.11 on 2026-03-01 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COLECTIVA', 'Colectiva')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('RENOVADA', 'Renovada')], default='ACTIVA', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valor_canon', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_prima', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tomador', models.CharField(max_length=100)),
                ('asegurado', models.CharField(max_length=100)),
                ('beneficiario', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='polizas.poliza')),
            ],
        ),
    ]
